server: "hub-cloud.browserstack.com"
user: "herbertlima1"
key: "VqyKiDyXSx6KTK29PEp9"

common_caps:
  "browserstack.debug": true

browser_caps:
  -
    "os": "Windows"
    "os_version": "10"
    "browser": "Chrome"
    "browser_version": "60.0"
    "resolution": "1024x768"